version: '3.8'
services:
  mongodb:
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - data:/data/db
volumes:
  data:
