version: '3.8'
services:
  mongodb:
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - '127.0.0.1:27017:27017'
    volumes:
      - data:/data/db
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  data:
  grafana_data:
