version: 2.1
jobs:
  build:
    docker:
      - image: python:3.11
      - image: mongo:latest

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      - run:
          name: Install pytest
          command: pip install pytest

      - run:
          name: Start MongoDB
          command: docker run --name mongodb -d -p 27017:27017 mongo:latest

      - run:
          name: Run Tests
          command: pytest

      - run:
          name: Stop MongoDB
          command: docker stop mongodb

workflows:
  version: 2
  build:
    jobs:
      - build
