version: 2.1
jobs:
  build:
    docker:
      - image: python:3.11

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: pip install -r requirements.txt

      - run:
          name: Install pytest
          command: pip install pytest

      - run:
          name: Run Tests
          command: pytest

workflows:
  version: 2
  build:
    jobs:
      - build