#!/usr/bin/env python
from argparse import ArgumentParser

from chess import WHITE, BLACK

from common.util import MODULES, load_module, map_color_option
from common.remote_engine import add_remotes

def add_module_subparsers(parser):
    subparsers = parser.add_subparsers(dest='command', required=True)
    for module in MODULES:
        action_module = load_module(module)
        action_module.add_subparser(module, subparsers)

if __name__ == '__main__':
    parser = ArgumentParser(
        prog='chess-insights', description='Chess Insights')
    add_module_subparsers(parser)
    args = parser.parse_args()
    map_color_option(args)
    if hasattr(args, 'remote_engines'):
        add_remotes(args.remote_engines)
    load_module(args.command).run(args)